apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb # Matches the label in the Deployment/StatefulSet
  type: ClusterIP # Internal IP. Change to NodePort or LoadBalancer for external access
