apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-init-job
spec:
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: mariadb-init
          image: mariadb:10.6

          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_ROOT_PASSWORD

          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MariaDB..."
              sleep 10

              echo "Installing envsubst..."
              apt-get update && apt-get install -y gettext-base

              echo "Running init script..."
              envsubst < /scripts/init.sql | mysql -h mariadb -u root -p$MYSQL_ROOT_PASSWORD

          volumeMounts:
            - name: init-script
              mountPath: /scripts

      volumes:
        - name: init-script
          configMap:
            name: mariadb-init